MVCTicariOtomasyon/Controllers/İstatistikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCTicariOtomasyon.Models.Siniflar;

namespace MVCTicariOtomasyon.Controllers
{
    
    public class İstatistikController : Controller
    {
        // GET: İstatistik
        Context c = new Context();
        public ActionResult Index()
        {
            var deger1 = c.Carilers.Count().ToString();
            ViewBag.d1 = deger1;
            var deger2 = c.Uruns.Count().ToString();
            ViewBag.d2 = deger2;
            var deger3 = c.Personels.Count().ToString();
            ViewBag.d3 = deger3;
            var deger4 = c.Kategoris.Count().ToString();
            ViewBag.d4 = deger1;
            var deger5 = c.Uruns.Sum(x=>x.Stok).ToString();
            ViewBag.d5 = deger5;
            var deger6 = (from x in c.Uruns select x.Marka).Distinct().Count().ToString(); 
            ViewBag.d6 = deger6;
            var deger7 = c.Uruns.Count(x=>x.Stok<=20).ToString();
            ViewBag.d7 = deger7;
            var deger8 = (from x in c.Uruns orderby x.SatisFiyat descending select x.UrunAd).FirstOrDefault();
            ViewBag.d8 = deger8;
            var deger9 = (from x in c.Uruns orderby x.SatisFiyat ascending select x.UrunAd).FirstOrDefault();
            ViewBag.d9 = deger9;
            var deger10 = c.Uruns.Count(x => x.UrunAd == "Buzdolabı").ToString();
            ViewBag.d10 = deger10;
            var deger11 = c.Uruns.Count(x => x.UrunAd == "Akıllı Süpürge").ToString();
            ViewBag.d11 = deger11;
            var deger12 = c.Uruns.GroupBy(x => x.Marka).OrderByDescending(z => z.Count()).Select(y => y.Key).FirstOrDefault();
            ViewBag.d12 = deger12;
            var deger13 =c.Uruns.Where(u=>u.UrunID==(c.SatisHarekets.GroupBy(x => x.Urunid).OrderByDescending(z =>z.Count
                ()).Select(y => y.Key).FirstOrDefault())).Select(k=>k.UrunAd).FirstOrDefault();
            ViewBag.d13 = deger13;

            var deger14 = c.SatisHarekets.Sum(x => x.ToplamTutar).ToString();
            ViewBag.d14 = deger14;

            DateTime bugun =  DateTime.Today;
            var deger15 = c.SatisHarekets.Count(x => x.Tarih==bugun).ToString();
            ViewBag.d15 = deger15;
          
            var deger16 = c.SatisHarekets.Where(x => x.Tarih == bugun).Sum(y =>(decimal?)y.ToplamTutar).ToString();
            ViewBag.d16 = deger16;
            
            return View();
        }
        public ActionResult KolayTablolar()
        {
            var sorgu = from x in c.Carilers
                        group x by x.CariSehir into g
                        select new SinifGrup
                        {
                            Sehir = g.Key,
                            Sayi = g.Count()
                        };
            return View(sorgu.ToList());
        }
        public PartialViewResult Partial1()
        {
            var sorgu2 = from x in c.Personels
                         group x by x.Departman.DepartmanAd into g
                         select new SinifGrup2
                         {
                             Departman = g.Key,
                             Sayi = g.Count()
                         };
            return PartialView(sorgu2.ToList());
        }
        public PartialViewResult Partial2()
        {
            var sorgu = c.Carilers.ToList();
            return PartialView(sorgu);
        }
        public PartialViewResult Partial3()
        {
            var sorgu = c.Uruns.ToList();
            return PartialView(sorgu);
        }
        public PartialViewResult Partial4()
        {
            var sorgu = from x in c.Uruns
                         group x by x.Marka into g
                         select new SinifGrup3
                         {
                             marka = g.Key,
                             sayi = g.Count()
                         };
            return PartialView(sorgu);
        }
    }
}

MVCTicariOtomasyon/Views/İstatistik/KolayTablolar.cshtml
@model IEnumerable<MVCTicariOtomasyon.Models.Siniflar.SinifGrup>
@{
    ViewBag.Title = "KolayTablolar";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Simple Tables</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">  
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Basit Tablolar</h1>
                        </div>
                      
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Kategori Tablosu</h3>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th style="width: 10px">#</th>
                                                <th>Kategori Adı</th>
                                                <th>Progress Bar</th>
                                                <th style="width: 40px">Oran</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>1.</td>
                                                <td>Beyaz Eşya</td>
                                                <td>
                                                    <div class="progress progress-xs">
                                                        <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                    </div>
                                                </td>
                                                <td><span class="badge bg-danger">55%</span></td>
                                            </tr>
                                            <tr>
                                                <td>2.</td>
                                                <td>Küçük Ev Aletleri</td>
                                                <td>
                                                    <div class="progress progress-xs">
                                                        <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                    </div>
                                                </td>
                                                <td><span class="badge bg-warning">70%</span></td>
                                            </tr>
                                            <tr>
                                                <td>3.</td>
                                                <td>Bilgisayar</td>
                                                <td>
                                                    <div class="progress progress-xs progress-striped active">
                                                        <div class="progress-bar bg-primary" style="width: 30%"></div>
                                                    </div>
                                                </td>
                                                <td><span class="badge bg-primary">30%</span></td>
                                            </tr>
                                            <tr>
                                                <td>4.</td>
                                                <td>Mobilya</td>
                                                <td>
                                                    <div class="progress progress-xs progress-striped active">
                                                        <div class="progress-bar bg-success" style="width: 90%"></div>
                                                    </div>
                                                </td>
                                                <td><span class="badge bg-success">90%</span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>


                            </div>
                            <!-- /.card -->

                            @Html.Action("Partial1", "İstatistik")

                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Müşteri Şehir Tablosu</h3>

                                    <div class="card-tools">

                                    </div>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body p-0">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th style="width: 10px">#</th>
                                                <th>Şehir</th>
                                                <th>Progress Bar</th>
                                                <th style="width: 40px">Adet</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{int sirano = 0; }
                                            @foreach (var x in Model)
                                            {
                                                <tr>
                                                    <td>@{sirano++;}@sirano</td>
                                                    <td>@x.Sehir</td>
                                                    <td>
                                                        @if (x.Sayi == 1)
                                                        {
                                                            <div class="progress progress-xs">
                                                                <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                            </div>
                                                        }
                                                        @if (x.Sayi == 2)
                                                        {
                                                            <div class="progress progress-xs">
                                                                <div class="progress-bar bg-warning" style="width: 55%"></div>
                                                            </div>
                                                        }
                                                        @if (x.Sayi == 3)
                                                        {
                                                            <div class="progress progress-xs">
                                                                <div class="progress-bar bg-success" style="width: 55%"></div>
                                                            </div>
                                                        }
                                                        @if (x.Sayi > 3)
                                                        {
                                                            <div class="progress progress-xs">
                                                                <div class="progress-bar bg-black" style="width: 55%"></div>
                                                            </div>
                                                        }
                                                    </td>
                                                    <td>
                                                        @if (x.Sayi == 1)
                                                        {
                                                            <span class="badge bg-danger">@x.Sayi</span>}
                                                        @if (x.Sayi == 2)
                                                        {
                                                            <span class="badge bg-warning">@x.Sayi</span>}
                                                        @if (x.Sayi == 3)
                                                        {
                                                            <span class="badge bg-success">@x.Sayi</span>}
                                                        @if (x.Sayi > 3)
                                                        {
                                                            <span class="badge bg-black">@x.Sayi</span>}
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                            @Html.Action("Partial4","İstatistik")
                            
                            <!-- /.card -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->

                    @Html.Action("Partial2", "İstatistik")
                    <!-- /.row -->
                    @Html.Action("Partial3", "İstatistik")
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
    
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>

    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script>
</body>
</html>

MVCTicariOtomasyon/Views/İstatistik/Partial1.cshtml
@model IEnumerable<MVCTicariOtomasyon.Models.Siniflar.SinifGrup2>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Departman Personel Sayıları</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Departman</th>
                    <th>Progress Bar</th>
                    <th style="width: 40px">Sayı</th>
                </tr>
            </thead>
            <tbody>
                @{int sirano = 0; }
                @foreach (var x in Model)
                {
                    <tr>
                        <td>@{sirano++;}@sirano</td>
                        <td>@x.Departman</td>
                        <td>
                            @if (x.Sayi == 1)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (x.Sayi == 2)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width: 55%"></div>
                                </div>
                            }
                            @if (x.Sayi == 3)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-success" style="width: 55%"></div>
                                </div>
                            }
                            @if (x.Sayi > 3)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-black" style="width: 55%"></div>
                                </div>
                            }
                        </td>
                        <td>
                            @if (x.Sayi == 1)
                            {
                                <span class="badge bg-danger">@x.Sayi</span>}
                            @if (x.Sayi == 2)
                            {
                                <span class="badge bg-warning">@x.Sayi</span>}
                            @if (x.Sayi == 3)
                            {
                                <span class="badge bg-success">@x.Sayi</span>}
                            @if (x.Sayi > 3)
                            {
                                <span class="badge bg-black">@x.Sayi</span>}
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

MVCTicariOtomasyon/Views/İstatistik/Partial2.cshtml
@using MVCTicariOtomasyon.Models.Siniflar
@model List<Cariler>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Cariler Hover Tablosu</h3>

                    <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Ad</th>
                                <th>Soyad</th>
                                <th>Şehir</th>
                                <th>Mail</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var x in Model)
                            {
                                <tr>
                                    <td>@x.CariID</td>
                                    <td>@x.CariAd</td>
                                    <td>@x.CariSoyad</td>
                                    <td>@x.CariSehir</td>
                                    <td>@x.CariMaiil</td>
                                   
                                    </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>

MVCTicariOtomasyon/Views/İstatistik/Partial3.cshtml
@using MVCTicariOtomasyon.Models.Siniflar
@model List<Urun>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Ürün Bilgi Tablosu</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ürün Adı</th>
                            <th>Marka</th>
                            <th>Stok</th>
                            <th>Alış Fiyatı</th>
                            <th>Satış Fiyatı</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var x in Model)
                        {
                        <tr>
                            <td>@x.UrunID</td>
                            <td>@x.UrunAd</td>
                            <td>@x.Marka</td>
                            <td>@x.Stok</td>
                            <td>@x.AlisFiyat ₺</td>
                            <td>@x.SatisFiyat ₺</td>
                             </tr>
                        }
                        
                   
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

MVCTicariOtomasyon/Views/İstatistik/Partial4.cshtml
@model IEnumerable<MVCTicariOtomasyon.Models.Siniflar.SinifGrup3>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Ürün Marka Tablosu</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Marka</th>
                    <th>Progress Bar</th>
                    <th style="width: 40px">Toplam</th>
                </tr>
            </thead>
            <tbody>
                @{int sirano = 0; }
                @foreach (var x in Model)
                {
                    <tr>
                        <td>@{sirano++;}@sirano</td>
                        <td>@x.marka</td>
                        <td>
                            @if (x.sayi == 1)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (x.sayi == 2)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width: 55%"></div>
                                </div>
                            }
                            @if (x.sayi == 3)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-success" style="width: 55%"></div>
                                </div>
                            }
                            @if (x.sayi > 3)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-black" style="width: 55%"></div>
                                </div>
                            }
                        </td>
                        <td>
                            @if (x.sayi == 1)
                            {
                                <span class="badge bg-danger">@x.sayi</span>}
                            @if (x.sayi == 2)
                            {
                                <span class="badge bg-warning">@x.sayi</span>}
                            @if (x.sayi == 3)
                            {
                                <span class="badge bg-success">@x.sayi</span>}
                            @if (x.sayi > 3)
                            {
                                <span class="badge bg-black">@x.sayi</span>}
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>